name: "投稿年终总结"
description: "在这里发起新的 issue 以投稿您的年终总结"
title: "[New]: "
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        感谢你的投稿~ 🎉

        在此之前，请注意以下几点：
        - 投稿前请检查是否已被收录。
        - 请务必按以下格式填写 **issue 标题**：  
          `文章标题 - 网站名称`  
          示例：`如何写出优秀的年终总结 - 我的博客`
        - **文章链接**：请填写文章的原始链接。
  - type: input
    id: post_url
    attributes:
      label: "文章链接"
      description: "请填写文章的原始链接"
      placeholder: "https://example.com/"
    validations:
      required: true
